apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::458233137987:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-S60TS6PVA1ES
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::458233137987:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-09T16:42:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1839"
  uid: 11831792-baaf-4bac-ae72-4a42496c23d0
